apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-k8s
  labels:
    app: hello-k8s    
spec:
  selector:
    matchLabels:
      app: hello-k8s
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-k8s
    spec:
      containers:
        - name: hello-8s
          image: dpfefferatpivotal/hello-k8s:0.0.2
          imagePullPolicy: Always
          resources:
            requests:
              memory: "768Mi"
              cpu: "500m"
            limits:
              memory: "768Mi"
              cpu: "500m"          