apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-k8s
spec:
  rules:
  - host: hello-k8s.highgarden.tkg-aws-e2-lab.winterfell.live
    http:
      paths:
      - backend:
          serviceName: hello-k8s
          servicePort: 8080
