---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springio/spring-ci-base

inputs:
  - name: hello-k8s-repo

outputs:
  - name: hello-k8s-repo-compiled

caches:
  - path: .m2

run:
  path: hello-k8s-repo/ci/build.sh