resource_types:
  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.14"

resources:
  - name: hello-k8s-repo
    type: git
    source:
      uri: ((git-repo))

  - name: hello-k8s-image
    type: docker-image
    source:
      email: ((registry-email))
      username: ((registry-username))
      password: ((registry-password))
      repository: ((registry-url))/((registry-project))/hello-k8s
      insecure_registries: 
        - ((registry-host)):443
        - ((registry-host))

  - name: kubernetes-lab
    type: kubernetes
    source:
      server: ((k8s-server))
      namespace: default
      insecure_skip_tls_verify: true
      token: ((token))

jobs:
  - name: build-and-publish
    public: true
    serial: true
    plan:
      - get: hello-k8s-repo
        trigger: true
      - task: build
        file: hello-k8s-repo/ci/build.yaml
      - put: hello-k8s-image
        params:
          build: hello-k8s-repo-compiled
  - name: kubernetes-deploy-lab
    plan:
      - get: hello-k8s-repo
      - get: hello-k8s-image
        trigger: true
        passed: [build-and-publish]
      - put: kubernetes-lab
        params:
          kubectl: apply -f hello-k8s-repo/k8s/deployment.yaml
          wait_until_ready: 120
          wait_until_ready_selector: app=boot-backend